# Generated by Django 5.2.6 on 2025-09-12 11:11

import django.core.validators
import django.db.models.deletion
import mainapps.kyc.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_auto_approval', models.BooleanField(default=False)),
                ('auto_approval_countries', models.JSONField(default=list, help_text='List of countries eligible for auto-approval')),
                ('max_auto_approval_amount', models.DecimalField(decimal_places=8, default=1000, help_text='Maximum token amount for auto-approval', max_digits=20)),
                ('require_manual_review_for_high_risk', models.BooleanField(default=True)),
                ('review_expiry_days', models.PositiveIntegerField(default=365, help_text='Days until KYC approval expires')),
                ('require_proof_of_address', models.BooleanField(default=True)),
                ('require_selfie', models.BooleanField(default=True)),
                ('require_source_of_funds', models.BooleanField(default=False)),
                ('notify_on_submission', models.BooleanField(default=True)),
                ('notify_on_approval', models.BooleanField(default=True)),
                ('notify_on_rejection', models.BooleanField(default=True)),
                ('notify_on_expiry', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KYC Settings',
                'verbose_name_plural': 'KYC Settings',
                'db_table': 'kyc_settings',
            },
        ),
        migrations.CreateModel(
            name='KYCApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(blank=True, help_text='Auto-generated KYC application ID', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Investigation'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='low', max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('country_of_residence', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200, null=True)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('drivers_license', "Driver's License"), ('national_id', 'National ID Card'), ('residence_permit', 'Residence Permit')], max_length=20)),
                ('document_number', models.CharField(max_length=50)),
                ('document_expiry_date', models.DateField(blank=True, null=True)),
                ('document_issuing_country', models.CharField(max_length=100)),
                ('document_front', models.ImageField(help_text='Front side of ID document (max 5MB)', upload_to=mainapps.kyc.models.kyc_document_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf']), mainapps.kyc.models.validate_file_size])),
                ('document_back', models.ImageField(blank=True, help_text='Back side of ID document (if applicable, max 5MB)', null=True, upload_to=mainapps.kyc.models.kyc_document_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf']), mainapps.kyc.models.validate_file_size])),
                ('selfie_image', models.ImageField(help_text='Selfie with ID document (max 5MB)', upload_to=mainapps.kyc.models.kyc_document_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), mainapps.kyc.models.validate_file_size])),
                ('proof_of_address', models.ImageField(blank=True, help_text='Utility bill or bank statement (max 5MB)', null=True, upload_to=mainapps.kyc.models.kyc_document_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf']), mainapps.kyc.models.validate_file_size])),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('employer', models.CharField(blank=True, max_length=100, null=True)),
                ('annual_income_range', models.CharField(blank=True, choices=[('0-25k', '$0 - $25,000'), ('25k-50k', '$25,000 - $50,000'), ('50k-100k', '$50,000 - $100,000'), ('100k-250k', '$100,000 - $250,000'), ('250k+', '$250,000+')], max_length=50, null=True)),
                ('source_of_funds', models.TextField(blank=True, help_text='Describe the source of your cryptocurrency funds', null=True)),
                ('intended_use', models.TextField(help_text='Describe your intended use of ATC tokens')),
                ('crypto_experience', models.CharField(choices=[('beginner', 'Beginner (< 1 year)'), ('intermediate', 'Intermediate (1-3 years)'), ('advanced', 'Advanced (3+ years)')], default='beginner', max_length=20)),
                ('other_wallets', models.JSONField(blank=True, default=list, help_text='List of other wallet addresses you own')),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Application',
                'verbose_name_plural': 'KYC Applications',
                'db_table': 'kyc_application',
            },
        ),
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('sanctions', 'Sanctions Screening'), ('pep', 'Politically Exposed Person'), ('adverse_media', 'Adverse Media'), ('document_verification', 'Document Verification'), ('face_match', 'Face Matching'), ('address_verification', 'Address Verification')], max_length=30)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('manual_review', 'Manual Review Required'), ('error', 'Error')], max_length=20)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence score (0-100)', max_digits=5, null=True)),
                ('details', models.JSONField(default=dict, help_text='Detailed check results')),
                ('provider', models.CharField(blank=True, help_text='Third-party service provider', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kyc_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='kyc.kycapplication')),
            ],
            options={
                'verbose_name': 'Compliance Check',
                'verbose_name_plural': 'Compliance Checks',
                'db_table': 'kyc_compliance_check',
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('identity', 'Identity Document'), ('address', 'Proof of Address'), ('income', 'Proof of Income'), ('funds', 'Source of Funds'), ('other', 'Other')], max_length=20)),
                ('document_name', models.CharField(max_length=200)),
                ('document_file', models.FileField(upload_to=mainapps.kyc.models.kyc_document_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf']), mainapps.kyc.models.validate_file_size])),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('kyc_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='kyc.kycapplication')),
            ],
            options={
                'verbose_name': 'KYC Document',
                'verbose_name_plural': 'KYC Documents',
                'db_table': 'kyc_document',
            },
        ),
        migrations.CreateModel(
            name='KYCReviewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='Internal notes not visible to applicant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kyc_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_review_notes', to='kyc.kycapplication')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_review_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Review Note',
                'verbose_name_plural': 'KYC Review Notes',
                'db_table': 'kyc_review_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='kycapplication',
            index=models.Index(fields=['status', 'created_at'], name='kyc_applica_status_5fff3d_idx'),
        ),
        migrations.AddIndex(
            model_name='kycapplication',
            index=models.Index(fields=['user', 'status'], name='kyc_applica_user_id_d80d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='kycapplication',
            index=models.Index(fields=['application_id'], name='kyc_applica_applica_23f324_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='compliancecheck',
            unique_together={('kyc_application', 'check_type')},
        ),
    ]
