# Generated by Django 5.2.6 on 2025-09-16 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address'),
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycapplication',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='kycapplication',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='kycapplication',
            name='city',
        ),
        migrations.RemoveField(
            model_name='kycapplication',
            name='country_of_residence',
        ),
        migrations.RemoveField(
            model_name='kycapplication',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kyc_application', to='accounts.address'),
        ),
    ]
