# Generated by Django 5.2.6 on 2025-09-16 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0012_city_translations_country_translations_and_more'),
        ('kyc', '0002_remove_kycapplication_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycapplication',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kyc_application', to='cities_light.country'),
        ),
    ]
