# Generated by Django 5.2.6 on 2025-09-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_alter_kycapplication_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycapplication',
            name='document_issuing_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='document_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
