# Generated by Django 5.2.6 on 2025-09-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_alter_kycapplication_document_issuing_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycapplication',
            name='intended_use',
            field=models.TextField(blank=True, help_text='Describe your intended use of ATC tokens', null=True),
        ),
    ]
