# Generated by Django 5.2.6 on 2025-09-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_alter_kycapplication_intended_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycapplication',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
