# Generated by Django 5.2.6 on 2025-09-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0006_kycapplication_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycapplication',
            name='phone_number',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
