# Generated by Django 5.2.6 on 2025-09-17 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0012_city_translations_country_translations_and_more'),
        ('kyc', '0007_alter_kycapplication_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycapplication',
            name='document_issuing_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.country'),
        ),
    ]
