# Generated by Django 5.2.7 on 2025-10-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0008_alter_kycapplication_document_issuing_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycapplication',
            name='crypto_experience',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner (< 1 year)'), ('intermediate', 'Intermediate (1-3 years)'), ('advanced', 'Advanced (3+ years)')], default='beginner', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='document_type',
            field=models.CharField(blank=True, choices=[('passport', 'Passport'), ('drivers_license', "Driver's License"), ('national_id', 'National ID Card'), ('residence_permit', 'Residence Permit')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='other_wallets',
            field=models.JSONField(blank=True, default=list, help_text='List of other wallet addresses you own', null=True),
        ),
    ]
