# Generated by Django 5.2.8 on 2026-01-06 23:43

import django.db.models.deletion
import mainapps.kyc.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0009_alter_kycapplication_crypto_experience_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_ref', models.CharField(max_length=120, unique=True)),
                ('flw_ref', models.CharField(blank=True, max_length=120, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('review', 'Review'), ('successful', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_link', models.URLField(blank=True, null=True)),
                ('init_payload', models.JSONField(blank=True, default=dict)),
                ('last_webhook_payload', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to=mainapps.kyc.models.payment_receipt_path)),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('payment_rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_payment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='kyc_payment_user_id_819582_idx'), models.Index(fields=['tx_ref'], name='kyc_payment_tx_ref_100c65_idx')],
            },
        ),
    ]
