# Generated by Django 5.2.8 on 2026-01-07 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organisation_physical_address_user_address'),
        ('kyc', '0010_kycpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycapplication',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='kycapplication',
            name='origin_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kyc_origin_details', to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='kycapplication',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
