# Generated by Django 5.2.8 on 2026-04-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0011_kycapplication_first_name_kycapplication_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycpayment',
            name='chain_id',
            field=models.PositiveIntegerField(default=137),
        ),
        migrations.AddField(
            model_name='kycpayment',
            name='collection_wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='kycpayment',
            name='payer_wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='kycpayment',
            name='payment_tx_hash',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='kycpayment',
            name='required_token_amount',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=30),
        ),
        migrations.AddField(
            model_name='kycpayment',
            name='token_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='kycpayment',
            name='token_decimals',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='kycpayment',
            name='token_price_usd',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='kycpayment',
            name='token_symbol',
            field=models.CharField(default='GZC', max_length=20),
        ),
        migrations.AddField(
            model_name='kycpayment',
            name='verification_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='kycpayment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
