# Generated by Django 5.2.8 on 2026-05-14 09:04

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_has_setup_mfa_user_mfa_enabled_user_mfa_secret'),
        ('cities_light', '0012_city_translations_country_translations_and_more'),
        ('kyc', '0012_kycpayment_chain_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='kycapplication',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('document_number'), models.F('document_type'), models.F('document_issuing_country'), condition=models.Q(('document_number__isnull', False), models.Q(('document_number', ''), _negated=True), ('document_type__isnull', False), ('document_issuing_country__isnull', False)), name='uniq_kyc_doc_identity_ci'),
        ),
    ]
