# Generated by Django 5.2.6 on 2025-09-19 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('exemption_type', models.CharField(choices=[('full', 'Full Exemption'), ('partial', 'Partial Exemption')], max_length=20)),
                ('exemption_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhaleProtectionLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('max_transfer_amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('max_balance_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlacklistedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blacklisted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmartContractTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('transfer', 'Transfer'), ('mint', 'Mint'), ('burn', 'Burn'), ('approve', 'Approve'), ('commit_transfer', 'Commit Transfer'), ('reveal_transfer', 'Reveal Transfer'), ('setup_vesting', 'Setup Vesting'), ('release_vested', 'Release Vested')], max_length=20)),
                ('from_address', models.CharField(blank=True, max_length=42)),
                ('to_address', models.CharField(blank=True, max_length=42)),
                ('amount', models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True)),
                ('gas_price', models.DecimalField(blank=True, decimal_places=18, max_digits=36, null=True)),
                ('gas_limit', models.BigIntegerField(blank=True, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=66)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nonce', models.BigIntegerField(blank=True, null=True)),
                ('commitment', models.CharField(blank=True, max_length=66)),
                ('vesting_duration', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_contract_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommitRevealTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment', models.CharField(max_length=66, unique=True)),
                ('to_address', models.CharField(max_length=42)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('nonce', models.BigIntegerField()),
                ('commit_time', models.DateTimeField(auto_now_add=True)),
                ('revealed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit_reveal_transfer', to=settings.AUTH_USER_MODEL)),
                ('reveal_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_contract.smartcontracttransaction')),
            ],
        ),
        migrations.CreateModel(
            name='VestingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_address', models.CharField(max_length=42)),
                ('total_amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('released_amount', models.DecimalField(decimal_places=18, default=0, max_digits=36)),
                ('start_time', models.DateTimeField()),
                ('duration', models.BigIntegerField()),
                ('is_whale', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vesting_schedule', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MiningReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miner_address', models.CharField(max_length=42)),
                ('block_number', models.BigIntegerField()),
                ('reward_amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('transaction_hash', models.CharField(max_length=66)),
                ('claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_contract.smartcontracttransaction')),
            ],
            options={
                'unique_together': {('miner_address', 'block_number')},
            },
        ),
    ]
