# Generated by Django 5.2.6 on 2025-09-12 11:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('chain_id', models.PositiveIntegerField(unique=True)),
                ('rpc_url', models.URLField()),
                ('explorer_url', models.URLField()),
                ('native_currency_symbol', models.CharField(max_length=10)),
                ('is_testnet', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Blockchain Network',
                'verbose_name_plural': 'Blockchain Networks',
                'db_table': 'blockchain_network',
            },
        ),
        migrations.CreateModel(
            name='TokenContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=42)),
                ('token_name', models.CharField(default='AtlanteanCrown', max_length=100)),
                ('token_symbol', models.CharField(default='ATC', max_length=10)),
                ('decimals', models.PositiveIntegerField(default=18)),
                ('total_supply', models.DecimalField(decimal_places=18, default=Decimal('1000000000'), max_digits=30)),
                ('deployment_block', models.PositiveIntegerField(blank=True, null=True)),
                ('deployment_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.blockchainnetwork')),
            ],
            options={
                'verbose_name': 'Token Contract',
                'verbose_name_plural': 'Token Contracts',
                'db_table': 'blockchain_token_contract',
                'unique_together': {('network', 'contract_address')},
            },
        ),
        migrations.CreateModel(
            name='StakingPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pool_type', models.CharField(choices=[('fixed', 'Fixed Term'), ('flexible', 'Flexible'), ('validator', 'Validator Pool')], max_length=20)),
                ('minimum_stake', models.DecimalField(decimal_places=18, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('maximum_stake', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True)),
                ('annual_percentage_yield', models.DecimalField(decimal_places=2, help_text='APY percentage (e.g., 12.50 for 12.5%)', max_digits=5)),
                ('lock_period_days', models.PositiveIntegerField(default=0, help_text='Lock period in days (0 for flexible staking)')),
                ('total_staked', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=30)),
                ('max_pool_size', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('staking_contract_address', models.CharField(blank=True, max_length=42, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.tokencontract')),
            ],
            options={
                'verbose_name': 'Staking Pool',
                'verbose_name_plural': 'Staking Pools',
                'db_table': 'blockchain_staking_pool',
            },
        ),
        migrations.CreateModel(
            name='VestingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('vesting_type', models.CharField(choices=[('linear', 'Linear Vesting'), ('cliff', 'Cliff Vesting'), ('milestone', 'Milestone-based')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('cliff_duration_days', models.PositiveIntegerField(default=0)),
                ('vesting_duration_days', models.PositiveIntegerField()),
                ('amount_released', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=30)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('vesting_contract_address', models.CharField(blank=True, max_length=42, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('token_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.tokencontract')),
            ],
            options={
                'verbose_name': 'Vesting Schedule',
                'verbose_name_plural': 'Vesting Schedules',
                'db_table': 'blockchain_vesting_schedule',
            },
        ),
        migrations.CreateModel(
            name='BlockchainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=66)),
                ('log_index', models.PositiveIntegerField()),
                ('contract_address', models.CharField(max_length=42)),
                ('event_type', models.CharField(choices=[('transfer', 'Transfer'), ('approval', 'Approval'), ('stake', 'Stake'), ('unstake', 'Unstake'), ('reward_claim', 'Reward Claim'), ('vesting_release', 'Vesting Release'), ('whale_transfer', 'Whale Transfer')], max_length=20)),
                ('event_data', models.JSONField(default=dict)),
                ('block_number', models.PositiveIntegerField()),
                ('block_timestamp', models.DateTimeField()),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.blockchainnetwork')),
            ],
            options={
                'db_table': 'blockchain_event',
                'ordering': ['-block_number', '-log_index'],
                'indexes': [models.Index(fields=['event_type', 'is_processed'], name='blockchain__event_t_6a80ac_idx'), models.Index(fields=['block_number'], name='blockchain__block_n_8fcad0_idx'), models.Index(fields=['contract_address'], name='blockchain__contrac_ed06c7_idx')],
                'unique_together': {('tx_hash', 'log_index')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('block_number', models.PositiveIntegerField(blank=True, null=True)),
                ('block_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('transaction_index', models.PositiveIntegerField(blank=True, null=True)),
                ('from_address', models.CharField(max_length=42)),
                ('to_address', models.CharField(max_length=42)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('gas_used', models.PositiveIntegerField(blank=True, null=True)),
                ('gas_price', models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True)),
                ('transaction_fee', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True)),
                ('transaction_type', models.CharField(choices=[('transfer', 'Transfer'), ('mint', 'Mint'), ('burn', 'Burn'), ('stake', 'Stake'), ('unstake', 'Unstake'), ('reward', 'Reward'), ('vesting', 'Vesting Release')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.blockchainnetwork')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('token_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.tokencontract')),
            ],
            options={
                'db_table': 'blockchain_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tx_hash'], name='blockchain__tx_hash_64a17a_idx'), models.Index(fields=['from_address', 'to_address'], name='blockchain__from_ad_c282a7_idx'), models.Index(fields=['from_user', 'to_user'], name='blockchain__from_us_728bd1_idx'), models.Index(fields=['status', 'created_at'], name='blockchain__status_f05873_idx'), models.Index(fields=['transaction_type'], name='blockchain__transac_e15dcb_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserStake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staked_amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('rewards_earned', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=30)),
                ('rewards_claimed', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=30)),
                ('staked_at', models.DateTimeField(auto_now_add=True)),
                ('unlock_at', models.DateTimeField(blank=True, null=True)),
                ('unstaked_at', models.DateTimeField(blank=True, null=True)),
                ('last_reward_calculation', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('unstaking', 'Unstaking'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('stake_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('unstake_tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('staking_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.stakingpool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blockchain_user_stake',
                'indexes': [models.Index(fields=['user', 'status'], name='blockchain__user_id_b8ff19_idx'), models.Index(fields=['staking_pool', 'status'], name='blockchain__staking_428b4c_idx'), models.Index(fields=['staked_at'], name='blockchain__staked__810687_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('block_number', models.PositiveIntegerField(blank=True, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.blockchainnetwork')),
                ('token_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.tokencontract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blockchain_wallet_balance',
                'indexes': [models.Index(fields=['user', 'network'], name='blockchain__user_id_b9f5eb_idx'), models.Index(fields=['last_updated'], name='blockchain__last_up_c88afb_idx')],
                'unique_together': {('user', 'network', 'token_contract')},
            },
        ),
    ]
