# Generated by Django 5.2.8 on 2026-01-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_token_purchase'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tokenpurchase',
            new_name='blockchain__user_id_f2b571_idx',
            old_name='blockchain_user_id_1a3309_idx',
        ),
        migrations.RenameIndex(
            model_name='tokenpurchase',
            new_name='blockchain__tx_ref_60f40a_idx',
            old_name='blockchain_tx_ref_5a5d37_idx',
        ),
    ]
