# Generated by Django 5.2.6 on 2025-09-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organisation_user_organisation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='verificationcode',
            name='accounts_ve_user_id_0d0e3b_idx',
        ),
        migrations.RemoveField(
            model_name='verificationcode',
            name='is_used',
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['user', 'verification_type'], name='accounts_ve_user_id_45597a_idx'),
        ),
    ]
