# Generated by Django 5.2.6 on 2025-09-17 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='physical_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organisation', to='accounts.address'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='accounts.address'),
        ),
    ]
