# Generated by Django 5.2.8 on 2026-01-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_has_been_kyc_rewarded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='atc_balance',
        ),
    ]
