# Generated by Django 5.2.8 on 2026-05-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_atc_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_setup_mfa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
