# Generated by Django 5.2.6 on 2025-09-19 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletCreationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(max_length=42)),
                ('recovery_phrase_hash', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_creation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_creation_log',
                'indexes': [models.Index(fields=['user'], name='wallet_crea_user_id_e3f117_idx'), models.Index(fields=['created_at'], name='wallet_crea_created_fbec86_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletRecoveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_recovery_attempt',
                'indexes': [models.Index(fields=['user', 'success'], name='wallet_reco_user_id_1a2e7d_idx'), models.Index(fields=['created_at'], name='wallet_reco_created_04d181_idx')],
            },
        ),
        migrations.CreateModel(
            name='WalletSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=64, unique=True)),
                ('encrypted_private_key', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_session',
                'indexes': [models.Index(fields=['user', 'is_active'], name='wallet_sess_user_id_e10238_idx'), models.Index(fields=['session_token'], name='wallet_sess_session_783491_idx'), models.Index(fields=['expires_at'], name='wallet_sess_expires_e93abb_idx')],
            },
        ),
    ]
